name : CI pipeline
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t fraud-detection-app .

      - name: Run container briefly to verify build
        run: |
          docker run --rm -d -p 5005:5005 fraud-detection-app
          sleep 10

      
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker tag fraud-detection-app:latest ${{ secrets.DOCKER_USERNAME }}/credit-fraud-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/credit-fraud-app:latest

